### ISSUE TITLE
Generic exception - Backend Test pages Error - Json file

### ISSUE THREAD

**Issue by Zaltan15** [bobopinna/moodle-local_coursefisher#1]
When I run the Backend test page i get the error: 

`"Exception - count(): Argument #1 ($value) must be of type Countable|array, stdClass given"`

The file to test is a Json file.
Moodle version 4.1.1
PHP version 8.0.27

**Comment by bobopinna** [comment]
Fixed with commit 6bb8e44.

Thanks a lot.
